---
deployment:
  tasks:
    - export DEPLOYPATH=/home/heydarnd/public_html/kanalgames
    - /bin/cp -R public/css $DEPLOYPATH
    - /bin/cp -R public/fonts $DEPLOYPATH
    - /bin/cp -R public/img $DEPLOYPATH
    - /bin/cp -R public/js $DEPLOYPATH
    - export DEPLOYPATH=/home/heydarnd/web-kanalgame
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R tests $DEPLOYPATH
    - /bin/cp -R tests $DEPLOYPATH
    - /bin/cp LICENSE $DEPLOYPATH
    - /bin/cp builds $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp phpunit.xml.dist $DEPLOYPATH
    - /bin/cp spark $DEPLOYPATH
