<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- favicon pada title bar -->
    <link rel="apple-touch-icon" sizes="180x180" href="/img/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/img/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/img/favicon/favicon-16x16.png">
    <link rel="manifest" href="/img/favicon/site.webmanifest">
    <link rel="mask-icon" href="/img/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <!-- akan menerima kiriman key bernama'title_bar' milik array. dikirim
    oleh controller -->
    <title>Kanal Game | <?= $title_bar; ?></title>

    <!-- font family from Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500&family=Press+Start+2P&display=swap" rel="stylesheet">
    <!-- UI Kit css -->
    <link rel="stylesheet" href="/css/uikit.min.css">

    <!-- css using Materialize CSS -->
    <link rel="stylesheet" href="/css/materialize.min.css">

    <!-- material icon by Google Fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" crossorigin="anonymous">

    <!-- font awesome icon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- bootstrap 5 icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" crossorigin="anonymous">

    <!-- remixicon -->
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">

    <!-- box icon -->
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>



    <!-- color palette,generated by mycolor.space 
    Grey Friends-->
    <!-- #708090 -->
    <!-- #3a4856-->
    <!-- #8dafce-->
    <style>
        .button-section {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: row;

        }

        .button-inner-section {
            justify-content: space-between;

        }

        .button-inner-section>a {
            margin: 8px;
        }

        @media (max-width: 640px) {
            .button-section {
                display: flex;
                flex-direction: column;
            }



        }

        @font-face {
            font-family: sans-serif;
            font-style: normal;
            font-weight: 500;
            src: url(''), local();
        }

        .steam-download {
            color: white;
            border-radius: 16px;
            text-decoration: none;

        }

        .egs-download {
            color: white;
            background-color: #2a2a2a;
            border-radius: 16px;
            text-decoration: none;
        }

        .download-button {
            border-radius: 16px;
        }

        .container-about-1 {
            padding-bottom: 3rem !important;
            padding-top: 3rem !important;
            max-width: 960px;
            width: 100%;
            padding-right: 15px;
            padding-left: 15px;
            margin-right: auto;
            margin-left: auto;
        }
    </style>

</head>

<body>

    <?= $this->include('/layouts/navigation-bar/desktop'); ?>
    <?= $this->include('/layouts/navigation-bar/mobile-device'); ?>


    <!-- bagian isi dari tiap halaman -->
    <?= $this->renderSection('content'); ?>

    <!-- footer -->
    <?= $this->include('/layouts/footer'); ?>

    <!-- custom script -->
    <!-- <script src="/js/mystyle.js" async="true"></script> -->
    <!-- js using Materialize JS -->
    <script src="/js/materialize.min.js" async="true">
    </script>

    <!-- UI Kit js -->
    <script src="/js/uikit.min.js" async="true"></script>

    <!-- UI Kit icon  -->
    <script src="/js/uikit-icons.min.js" async="true"></script>

    <!-- Ion Icon -->
    <!-- <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script> -->

</body>

</html>