<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="description" content="KanalGame berisi info singkat dari game serta alamat untuk mengunduh game tersebut.">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- favicon pada title bar -->
    <link rel="apple-touch-icon" sizes="180x180" href="/img/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/img/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/img/favicon/favicon-16x16.png">
    <link rel="manifest" href="/img/favicon/site.webmanifest">
    <link rel="mask-icon" href="/img/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <!-- akan menerima kiriman key bernama'title_bar' milik array. dikirim
    oleh controller -->
    <title>Kanal Game | <?= $title_bar; ?></title>

    <!-- font family from Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500&family=Press+Start+2P&display=swap" rel="stylesheet">
    <!-- UI Kit css -->
    <link rel="stylesheet" href="/css/uikit.min.css" crossorigin="anonymous" referrerpolicy="no-referrer">
    <!-- custom styling css -->
    <link rel="stylesheet" href="/css/custom-styling.css" crossorigin="anonymous" referrerpolicy="no-referrer">
    <!-- css using Materialize CSS -->
    <link rel="stylesheet" href="/css/materialize.min.css" crossorigin="anonymous" referrerpolicy="no-referrer">

    <!-- material icon by Google Fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" crossorigin="anonymous" referrerpolicy="no-referrer">

    <!-- font awesome icon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" crossorigin="anonymous" referrerpolicy="no-referrer">

    <!-- bootstrap 5 icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" crossorigin="anonymous" referrerpolicy="no-referrer">

    <!-- remixicon -->
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet" crossorigin="anonymous" referrerpolicy="no-referrer">
    <!-- color palette,generated by mycolor.space 
    Grey Friends-->
    <!-- #708090 -->
    <!-- #3a4856-->
    <!-- #8dafce-->
    <style>
        /* press-start-2p-regular - latin */
        @font-face {
            font-family: 'Press Start 2P';
            font-style: normal;
            font-display: swap;
            font-weight: 400;
            src: url('/fonts/press-start-2p-v9-latin-regular.eot');
            /* IE9 Compat Modes */
            src: local(''),
                url('/fonts/press-start-2p-v9-latin-regular.eot?#iefix') format('embedded-opentype'),
                /* IE6-IE8 */
                url('/fonts/press-start-2p-v9-latin-regular.woff2') format('woff2'),
                /* Super Modern Browsers */
                url('/fonts/press-start-2p-v9-latin-regular.woff') format('woff'),
                /* Modern Browsers */
                url('/fonts/press-start-2p-v9-latin-regular.ttf') format('truetype'),
                /* Safari, Android, iOS */
                url('/fonts/press-start-2p-v9-latin-regular.svg#PressStart2P') format('svg');
            /* Legacy iOS */
        }

        /* barlow-condensed-500 - latin */
        @font-face {
            font-family: 'Barlow Condensed';
            font-display: swap;
            font-style: normal;
            font-weight: 500;
            src: url('/fonts/barlow-condensed-v5-latin-500.eot');
            /* IE9 Compat Modes */
            src: local(''),
                url('/fonts/barlow-condensed-v5-latin-500.eot?#iefix') format('embedded-opentype'),
                /* IE6-IE8 */
                url('/fonts/barlow-condensed-v5-latin-500.woff2') format('woff2'),
                /* Super Modern Browsers */
                url('/fonts/barlow-condensed-v5-latin-500.woff') format('woff'),
                /* Modern Browsers */
                url('/fonts/barlow-condensed-v5-latin-500.ttf') format('truetype'),
                /* Safari, Android, iOS */
                url('/fonts/barlow-condensed-v5-latin-500.svg#BarlowCondensed') format('svg');
            /* Legacy iOS */
        }

        .button-section {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: row;

        }

        .button-inner-section {
            justify-content: space-between;

        }

        .button-inner-section>a {
            margin: 8px;
        }

        @media (max-width: 640px) {
            .button-section {
                display: flex;
                flex-direction: column;
            }

        }

        .download-button {
            border-radius: 16px;
        }
    </style>

</head>

<body>

    <?= $this->include('/layouts/navigation-bar/desktop'); ?>
    <?= $this->include('/layouts/navigation-bar/mobile-device'); ?>


    <!-- bagian isi dari tiap halaman -->
    <?= $this->renderSection('content'); ?>

    <!-- footer -->
    <?= $this->include('/layouts/footer'); ?>

    <!-- custom script -->
    <!-- <script src="/js/mystyle.js" async="true"></script> -->
    <!-- js using Materialize JS -->
    <script src="/js/materialize.min.js" async="true" defer>
    </script>

    <!-- UI Kit js -->
    <script src="/js/uikit.min.js" async="true" defer></script>

    <!-- UI Kit icon  -->
    <script src="/js/uikit-icons.min.js" async="true" defer></script>
</body>

</html>